FROM node:20-alpine

WORKDIR /app

COPY lib ./lib
COPY registration-service/package.json ./registration-service/
WORKDIR /app/registration-service
RUN npm install --omit=dev

COPY registration-service/. ./

RUN addgroup -S app && adduser -S app -G app && chown -R app:app /app
USER app

EXPOSE 3001
CMD ["node", "server.js"]
