FROM node:20-alpine

WORKDIR /app

COPY lib ./lib
COPY cronjob/package.json ./cronjob/
WORKDIR /app/cronjob
RUN npm install --omit=dev

COPY cronjob/. ./

RUN addgroup -S app && adduser -S app -G app && chown -R app:app /app
USER app

CMD ["node", "run.js"]
